name: Build Project

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    #defaults:
    #  run:
    #    working-directory: ./GTA5OnlineTools
    steps:
    #- uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.x
    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1.1
    - name: Clone repository
      run: git clone https://github.com/CrazyZhang666/GTA5OnlineTools.git --recurse-submodules
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.GITHUB_WORKSPACE}}
    - name: Build
      run: dotnet build --configuration Release
      working-directory: GTA5OnlineTools
    - name: Check if DLL got built
      run: if (-Not (Test-Path -path "bin/x64/Release/net6.0-windows/GTA5OnlineTools.dll")) {throw 1}
      working-directory: GTA5OnlineTools
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: binary
          path: |
            ${{env.GITHUB_WORKSPACE}}/bin/x64/Release/net6.0-windows/GTA5OnlineTools.dll
    - name: Generate Build Info
      id: var
      run: |
        echo "::set-output name=full_sha::$(git rev-parse HEAD)"
        echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      working-directory: GTA5OnlineTools
  check_detections:
    runs-on: ubuntu-latest
    name: Check for detections in Binary and notify if necesarry
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Test file for detected bits
        id: detections
        uses: Yimura/gtav-sigscan-action@v0.0.3
        with:
          file: ./GTA5OnlineTools.dll
  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: [ build ]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Echo build sha256
        id: build_sha
        run: |
          sha256sum GTA5OnlineTools.dll > sha256.checksum
          echo "::set-output name=build_sha::$(cat sha256.checksum)"
          cat sha256.checksum
      - name: Remove previous Nightly
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly [${{ needs.build.outputs.short_sha }}]
          tag_name: nightly
          body: |
            **This release has been build by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Build SHA256:
            ```
            ${{ steps.build_sha.outputs.build_sha }}
            ```
            To verify the build SHA256 during the action, click the build link, go-to "Create Release", open the Echo build sha256 step and read the sha256.
            Compare this build hash with one that you generated yourself from the build artifacts.
            Alternatively you can download the build artifacts, generate a SHA256 checksum and compare it with the below binary.
            Build artifacts ARE NOT automatically the same as release assets since release assets can be modified afterwards.
            These are builds of GTA5OnlineTools, they are provided for testing purposes only:
            - Test if your build environment produces a broken GTA5OnlineTools.dll
            - Test if source code is out of date and no longer compatible with the current version of GTA V
            If you wish to use this menu as-is you are on your own, no warranty is provided.
            Full Commit Hash:
            ```
            ${{ needs.build.outputs.full_sha }}
            ```
          files: |
            GTA5OnlineTools.dll
